Tests run py3 (#32929)
* Zeromq transport python3

* lets toss this fix in here, so that we get exception messages

* got states working

This forces the serializer to deserialize into strings on py3
but also allows for the argument 'raw' to be passed in allowing
for raw bytes to be sent explicitly. I made it this way
because the majority of calls are operational and the fileclient
is the only thing that needs bytes from the master

* all channels need to absorb the new raw arg

* Soem redundancy cleanup

* fix up base class

* try some more...

* Fix for "TypeError: send() got an unexpected keyword argument 'raw'"

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>

* fix an issue where we are making unicode strings bytes for no good reason